apiVersion: v2
name: erpnext
description: Kubernetes Helm Chart for the latest stable ERPNext branch
icon: https://fineto.fi/wp-content/uploads/2024/03/logo-noboarder-240x240tr.png
type: application
version: 7.0.98
appVersion: v15.31.3
dependencies:
- name: redis
  condition: redis-cache.enabled
  alias: redis-cache
  version: "17.15.2"
  repository: https://charts.bitnami.com/bitnami
- name: redis
  condition: redis-queue.enabled
  alias: redis-queue
  version: "17.15.2"
  repository: https://charts.bitnami.com/bitnami
- name: mariadb
  condition: mariadb.enabled
  version: "11.5.7"
  repository: https://charts.bitnami.com/bitnami
- name: postgresql
  condition: postgresql.enabled
  version: "12.1.6"
  repository: https://charts.bitnami.com/bitnami
